In [1]:
# Import the Data generator class from the ts_data_generator module 
from ts_data_generator import DataGen
from ts_data_generator.schema.models import AggregationType
from ts_data_generator.utils.functions import random_choice, random_int
from ts_data_generator.utils.trends import SinusoidalTrend, LinearTrend, WeekendTrend, StockTrend
import matplotlib.pyplot as plt
import random

In [2]:
d = DataGen()
d.start_datetime = "2019-01-01"
d.end_datetime = "2019-01-12"
d.to_granularity("h")


d.add_dimension("product", random_choice(["A", "B", "C", "D"]))
d.add_dimension(name="interface", function="X Y Z".split())

d.add_metric(
    name="sinusoidal", 
    trends=[
        SinusoidalTrend(name="sine", amplitude=6, freq=3, phase=0, noise_level=1.5)
    ],
    aggregation_type=AggregationType.SUM,
    )


d.add_metric(
    name="sinusoidal_linear", 
    trends=[
        SinusoidalTrend(name="sine", amplitude=3, freq=5, phase=0, noise_level=1.5),
        LinearTrend(name="linear", slope=30, offset=10, noise_level=1)
    ],
    aggregation_type=AggregationType.SUM,
)


def my_custom_function():
    while True:
        val1 = random.randint(1,2)
        val2 =  random.randint(1,3)
        # val3 = val1 + val2
        yield (val1, val2)

d.add_multi_items(names="val1 val2".split(), function=my_custom_function(), aggregation_type=[AggregationType.SUM, AggregationType.AVG])
d.add_multi_items(names="val3 val4".split(), function=my_custom_function())

In [3]:
d.data

,epoch,product,interface,sinusoidal,sinusoidal_linear,val1,val2,val3,val4
2019-01-01 00:00:00,1546300800,C,X,-2.312767,9.055882,2,2,1,1
2019-01-01 01:00:00,1546304400,C,Y,-0.509020,11.978673,1,2,2,3
2019-01-01 02:00:00,1546308000,C,Z,0.108050,15.016924,1,3,1,3
2019-01-01 03:00:00,1546311600,C,X,1.731398,11.893498,1,3,1,3
2019-01-01 04:00:00,1546315200,D,Y,1.289027,11.223924,2,1,1,1
...,...,...,...,...,...,...,...,...,...
2019-01-11 20:00:00,1547236800,A,Z,-6.276472,161.707118,2,1,1,1
2019-01-11 21:00:00,1547240400,D,X,-2.863229,165.375916,1,1,1,2
2019-01-11 22:00:00,1547244000,D,Y,-2.335643,165.613557,2,3,1,3
2019-01-11 23:00:00,1547247600,A,Z,-4.066051,166.590208,1,1,2,1
2019-01-12 00:00:00,1547251200,D,X,-4.287898,165.330133,2,2,2,3

In [4]:
d.aggregate(granularity="ME")

,product,interface,val3,val4,sinusoidal,sinusoidal_linear,val1,val2,epoch
index,,,,,,,,,
2019-01-31,A,X,1,1,7.540890,124.447484,3,2.333333,1548892800
2019-01-31,A,X,1,2,-1.721422,308.394454,6,2.250000,1548892800
2019-01-31,A,X,1,3,6.053338,166.198046,4,2.500000,1548892800
2019-01-31,A,X,2,1,5.599449,54.357980,1,2.000000,1548892800
2019-01-31,A,X,2,2,3.421607,401.934187,6,2.500000,1548892800
...,...,...,...,...,...,...,...,...,...
2019-01-31,D,Z,1,2,4.117071,236.549590,6,2.500000,1548892800
2019-01-31,D,Z,1,3,-9.464333,213.650967,3,2.000000,1548892800
2019-01-31,D,Z,2,1,-11.424783,369.130070,4,1.750000,1548892800
2019-01-31,D,Z,2,2,-5.694282,347.379917,5,2.000000,1548892800
2019-01-31,D,Z,2,3,-4.992799,384.281492,6,1.500000,1548892800