In [1]:
# Import the Data generator class from the ts_data_generator module 
from ts_data_generator import DataGen
from ts_data_generator.schema.models import AggregationType
from ts_data_generator.utils.functions import random_choice, random_int
from ts_data_generator.utils.trends import SinusoidalTrend, LinearTrend, WeekendTrend, StockTrend
import matplotlib.pyplot as plt
import random

In [2]:
d = DataGen()
d.start_datetime = "2019-01-01"
d.end_datetime = "2019-01-12"
d.to_granularity("h")


d.add_dimension("product", random_choice(["A", "B", "C", "D"]))
d.add_dimension(name="interface", function="X Y Z".split())

d.add_metric(
    name="sinusoidal", 
    trends=[
        SinusoidalTrend(name="sine", amplitude=6, freq=3, phase=0, noise_level=1.5)
    ],
    aggregation_type=AggregationType.SUM,
    )


d.add_metric(
    name="sinusoidal_linear", 
    trends=[
        SinusoidalTrend(name="sine", amplitude=3, freq=5, phase=0, noise_level=1.5),
        LinearTrend(name="linear", limit=30, offset=10, noise_level=1)
    ],
    aggregation_type=AggregationType.SUM,
)


def my_custom_function():
    while True:
        val1 = random.randint(1,2)
        val2 =  random.randint(1,3)
        # val3 = val1 + val2
        yield (val1, val2)

d.add_multi_items(names="val1 val2".split(), function=my_custom_function(), aggregation_type=[AggregationType.SUM, AggregationType.AVG])
d.add_multi_items(names="val3 val4".split(), function=my_custom_function())

In [3]:
d.data

,epoch,product,interface,sinusoidal,sinusoidal_linear,val1,val2,val3,val4
2019-01-01 00:00:00,1546300800,B,X,0.764504,6.259316,2,3,1,2
2019-01-01 01:00:00,1546304400,C,Y,0.892926,9.721257,1,3,2,2
2019-01-01 02:00:00,1546308000,A,Z,-0.106844,9.343756,1,2,1,3
2019-01-01 03:00:00,1546311600,D,X,3.350554,7.614888,1,3,1,3
2019-01-01 04:00:00,1546315200,C,Y,-1.451420,9.438136,1,3,2,1
...,...,...,...,...,...,...,...,...,...
2019-01-11 20:00:00,1547236800,D,Z,-6.518482,18.147395,1,1,1,2
2019-01-11 21:00:00,1547240400,D,X,-4.978932,16.070180,1,2,2,3
2019-01-11 22:00:00,1547244000,D,Y,-7.271939,15.795318,1,3,2,2
2019-01-11 23:00:00,1547247600,B,Z,-2.632455,18.523950,1,2,2,2
2019-01-12 00:00:00,1547251200,A,X,-6.076693,16.929833,2,3,1,3

In [4]:
d.aggregate(granularity="ME")

,product,interface,val3,val4,sinusoidal,sinusoidal_linear,val1,val2,epoch
index,,,,,,,,,
2019-01-31,A,X,1,1,7.588238,37.483102,5,2.000000,1548892800
2019-01-31,A,X,1,2,-4.825352,14.116858,2,3.000000,1548892800
2019-01-31,A,X,1,3,-3.536907,61.819420,6,2.400000,1548892800
2019-01-31,A,X,2,1,8.481537,52.756905,6,1.600000,1548892800
2019-01-31,A,X,2,2,-0.350846,72.402077,9,2.166667,1548892800
...,...,...,...,...,...,...,...,...,...
2019-01-31,D,Z,1,2,-7.802623,62.221853,5,1.600000,1548892800
2019-01-31,D,Z,1,3,-3.846974,34.907593,4,2.333333,1548892800
2019-01-31,D,Z,2,1,6.820343,72.775891,10,2.000000,1548892800
2019-01-31,D,Z,2,2,5.640524,60.856974,6,1.400000,1548892800
2019-01-31,D,Z,2,3,15.169581,45.711718,7,2.250000,1548892800